#!/bin/sh
PREFIX=arm-linux-gnueabi
CFLAGS="-Os -fno-stack-protector -fno-builtin -nostdinc"
${PREFIX}-as -meabi=4 -o init.o init.S
${PREFIX}-gcc $CFLAGS -c main.c -fPIC
${PREFIX}-gcc $CFLAGS -c console.c -fPIC
${PREFIX}-gcc $CFLAGS -c vsprintf.c -fPIC
${PREFIX}-gcc $CFLAGS -c printf.c -fPIC
${PREFIX}-gcc $CFLAGS -c font_8x8.c -fPIC
${PREFIX}-gcc $CFLAGS -c memstr.c -fPIC
${PREFIX}-gcc $CFLAGS -c font.c -fPIC
${PREFIX}-gcc $CFLAGS -c gpt.c -fPIC
${PREFIX}-gcc $CFLAGS -c ipu.c -fPIC
${PREFIX}-gcc $CFLAGS -c atag.c -fPIC
${PREFIX}-gcc $CFLAGS -c crc32.c -fPIC
${PREFIX}-gcc $CFLAGS -c hw_misc.c -fPIC
${PREFIX}-gcc $CFLAGS -c mu.c -fPIC
${PREFIX}-gcc -static -T ld-script -nostdlib -o boot.elf init.o main.o console.o vsprintf.o printf.o font_8x8.o memstr.o font.o gpt.o ipu.o atag.o crc32.o hw_misc.o mu.o -lgcc
${PREFIX}-objcopy -O binary -R .note -R .comment -S boot.elf boot
